"""Render the cross-engine conformance results as a markdown report.

Run as a module to (re)generate ``verification/reports/card_stat_conformance.md``:

    python -m verification.report
"""
from __future__ import annotations

from pathlib import Path

from .conformance import AGREE, DIVERGE, NA, CardComparison, run_conformance
from .name_map import NO_ORACLE_COUNTERPART
from .oracle_data import load_provenance

REPORT_PATH = Path(__file__).resolve().parent / "reports" / "card_stat_conformance.md"
STAT_ORDER = ["mana", "hp", "damage", "hit_speed", "range", "sight_range", "speed", "radius"]


def _fmt(v) -> str:
    if v is None:
        return "—"
    if isinstance(v, float):
        return f"{v:g}"
    return str(v)


def _counts(comparisons: list[CardComparison]) -> dict[str, dict[str, int]]:
    out: dict[str, dict[str, int]] = {}
    for c in comparisons:
        for stat, r in c.stats.items():
            bucket = out.setdefault(stat, {AGREE: 0, DIVERGE: 0, NA: 0})
            bucket[r.status] += 1
    return out


def render(comparisons: list[CardComparison], meta: dict) -> str:
    prov = load_provenance()
    counts = _counts(comparisons)
    diverging = [c for c in comparisons if c.divergences]

    lines: list[str] = []
    lines.append("# Cross-engine card-stat conformance")
    lines.append("")
    lines.append(
        "Generated by `python -m verification.report`. Compares crsim `CARD_DEFS` "
        "against the vendored stats of the second engine "
        f"([clash-simulator]({prov['source_repo']}) @ `{prov['commit'][:10]}`, "
        f"gamedata `{prov['gamedata_fingerprint'][:10]}`)."
    )
    lines.append("")
    lines.append(
        f"**Coverage:** {meta['mapped']}/{meta['crsim_cards']} crsim cards mapped to an "
        f"oracle card ({meta['oracle_cards']} oracle cards available). "
        f"{len(NO_ORACLE_COUNTERPART)} crsim cards have no oracle counterpart."
    )
    lines.append("")

    lines.append("## Agreement by stat")
    lines.append("")
    lines.append("| Stat | Agree | Diverge | N/A |")
    lines.append("|------|------:|--------:|----:|")
    for stat in STAT_ORDER:
        if stat in counts:
            b = counts[stat]
            lines.append(f"| {stat} | {b[AGREE]} | {b[DIVERGE]} | {b[NA]} |")
    lines.append("")

    lines.append("## Divergences")
    lines.append("")
    if not diverging:
        lines.append("None beyond tolerance.")
    else:
        lines.append("Stats outside tolerance. `na` stats (schema differences) are omitted.")
        lines.append("")
        lines.append("| Card | Oracle | Kind | Stat | crsim | oracle | diff |")
        lines.append("|------|--------|------|------|------:|-------:|-----:|")
        for c in diverging:
            for stat in c.divergences:
                r = c.stats[stat]
                pct = f"{r.pct:.0f}%" if r.pct is not None else "—"
                lines.append(
                    f"| {c.crsim_name} | {c.oracle_name} | {c.kind} | {stat} | "
                    f"{_fmt(r.ours)} | {_fmt(r.oracle)} | {pct} |"
                )
    lines.append("")

    lines.append("## No oracle counterpart")
    lines.append("")
    lines.append(", ".join(f"`{n}`" for n in sorted(NO_ORACLE_COUNTERPART)) or "None")
    lines.append("")
    return "\n".join(lines)


def main() -> None:
    comparisons, meta = run_conformance()
    text = render(comparisons, meta)
    REPORT_PATH.parent.mkdir(parents=True, exist_ok=True)
    REPORT_PATH.write_text(text)
    print(f"Wrote {REPORT_PATH}")


if __name__ == "__main__":
    main()
