"""Card definitions for all 125 Clash Royale cards (auto-generated).

Generated from ClashStrategic/stats data.
Tournament standard (Level 11) stats.
"""

from __future__ import annotations

import enum
from dataclasses import dataclass


class CardType(enum.IntEnum):
    KNIGHT = 0
    ARCHERS = 1
    GOBLINS = 2
    GIANT = 3
    PEKKA = 4
    MINIONS = 5
    BALLOON = 6
    WITCH = 7
    BARBARIANS = 8
    GOLEM = 9
    SKELETONS = 10
    VALKYRIE = 11
    SKELETON_ARMY = 12
    BOMBER = 13
    MUSKETEER = 14
    BABY_DRAGON = 15
    PRINCE = 16
    WIZARD = 17
    MINI_PEKKA = 18
    SPEAR_GOBLINS = 19
    GIANT_SKELETON = 20
    HOG_RIDER = 21
    MINION_HORDE = 22
    ICE_WIZARD = 23
    ROYAL_GIANT = 24
    GUARDS = 25
    PRINCESS = 26
    DARK_PRINCE = 27
    THREE_MUSKETEERS = 28
    LAVA_HOUND = 29
    ICE_SPIRIT = 30
    FIRE_SPIRIT = 31
    MINER = 32
    SPARKY = 33
    BOWLER = 34
    LUMBERJACK = 35
    BATTLE_RAM = 36
    INFERNO_DRAGON = 37
    ICE_GOLEM = 38
    MEGA_MINION = 39
    DART_GOBLIN = 40
    GOBLIN_GANG = 41
    ELECTRO_WIZARD = 42
    ELITE_BARBARIANS = 43
    HUNTER = 44
    EXECUTIONER = 45
    BANDIT = 46
    ROYAL_RECRUITS = 47
    NIGHT_WITCH = 48
    BATS = 49
    ROYAL_GHOST = 50
    RAM_RIDER = 51
    ZAPPIES = 52
    RASCALS = 53
    CANNON_CART = 54
    MEGA_KNIGHT = 55
    SKELETON_BARREL = 56
    FLYING_MACHINE = 57
    WALL_BREAKERS = 58
    ROYAL_HOGS = 59
    GOBLIN_GIANT = 60
    FISHERMAN = 61
    MAGIC_ARCHER = 62
    ELECTRO_DRAGON = 63
    FIRECRACKER = 64
    MIGHTY_MINER = 65
    ELIXIR_GOLEM = 66
    BATTLE_HEALER = 67
    SKELETON_KING = 68
    ARCHER_QUEEN = 69
    GOLDEN_KNIGHT = 70
    MONK = 71
    SKELETON_DRAGONS = 72
    MOTHER_WITCH = 73
    ELECTRO_SPIRIT = 74
    ELECTRO_GIANT = 75
    PHOENIX = 76
    LITTLE_PRINCE = 77
    GOBLIN_DEMOLISHER = 78
    GOBLIN_MACHINE = 79
    SUSPICIOUS_BUSH = 80
    GOBLINSTEIN = 81
    RUNE_GIANT = 82
    BERSERKER = 83
    BOSS_BANDIT = 84
    CANNON = 85
    GOBLIN_HUT = 86
    MORTAR = 87
    INFERNO_TOWER = 88
    BOMB_TOWER = 89
    BARBARIAN_HUT = 90
    TESLA = 91
    ELIXIR_COLLECTOR = 92
    X_BOW = 93
    TOMBSTONE = 94
    FURNACE = 95
    GOBLIN_CAGE = 96
    GOBLIN_DRILL = 97
    FIREBALL = 98
    ARROWS = 99
    RAGE = 100
    ROCKET = 101
    GOBLIN_BARREL = 102
    FREEZE = 103
    MIRROR = 104
    LIGHTNING = 105
    ZAP = 106
    POISON = 107
    GRAVEYARD = 108
    THE_LOG = 109
    TORNADO = 110
    CLONE = 111
    EARTHQUAKE = 112
    BARBARIAN_BARREL = 113
    HEAL_SPIRIT = 114
    GIANT_SNOWBALL = 115
    ROYAL_DELIVERY = 116
    VOID = 117
    GOBLIN_CURSE = 118
    SPIRIT_EMPRESS = 119
    VINES = 120
    GOBLIN_BRAWLER = 121
    BUSH_GOBLINS = 122
    CURSED_HOG = 123
    GUARDIENNE = 124


class EntityKind(enum.IntEnum):
    TROOP = 0
    SPELL = 1
    BUILDING = 2


class TargetMode(enum.IntEnum):
    GROUND = 0
    AIR_GROUND = 1
    BUILDINGS = 2
    AREA = 3


@dataclass(frozen=True, slots=True)
class CardDef:
    """Immutable definition of a card's base stats at Level 11."""
    card_type: CardType
    kind: EntityKind
    cost: int
    hp: float
    dps: float
    damage_per_hit: float
    hit_speed: float  # seconds between attacks
    load_time: float  # first attack pre-load
    speed: float  # tiles/sec
    attack_range: float  # tiles
    sight_range: float  # tiles
    target_mode: TargetMode
    is_flying: bool = False
    is_splash: bool = False
    splash_radius: float = 0.0
    spawn_count: int = 1
    deploy_time: float = 1.0
    collision_radius: float = 0.5
    mass: float = 6.0  # determines push priority (Knight=6, Giant=18, Skeleton=1)
    has_projectile: bool = False
    projectile_speed: float = 0.0  # tiles/sec for ranged attacks; 0 = melee/instant
    tower_damage: float = 0.0  # legacy/unused; superseded by crown_tower_damage_percent
    # Crown-tower damage modifier as a signed percent (authentic
    # ``crown_tower_damage_percent``): -70 means a crown tower takes 30% of the
    # normal damage (Fireball/Arrows/Zap), -75 Rocket/Miner, -80 The Log.
    crown_tower_damage_percent: float = 0.0
    building_lifetime: float = 0.0
    has_evolution: bool = False
    is_champion: bool = False
    has_hero: bool = False
    # Champion ability (manually activated). ability_cost is the extra elixir to
    # activate; ability_cooldown is seconds before it can fire again; values are
    # hand-curated from live-game data since the CSV export leaves them at 0.
    ability_cost: int = 0
    ability_cooldown: float = 0.0
    ability_duration: float = 0.0
    # Death spawn
    death_spawn_card: CardType | None = None
    death_spawn_count: int = 0
    # Combat fields (for game.py simulation)
    spawn_hp: float = 0.0
    spawn_dps: float = 0.0
    has_charge: bool = False
    charge_speed: float = 0.0
    charge_damage_mult: float = 2.0
    has_shield: bool = False
    shield_hp: float = 0.0
    has_knockback: bool = False
    knockback_distance: float = 0.0
    stuns: bool = False
    stun_duration: float = 0.0
    resets_inferno: bool = False
    death_spawn_hp: float = 0.0
    death_spawn_dps: float = 0.0
    inferno_dps_min: float = 0.0
    inferno_dps_max: float = 0.0
    spawner_interval: float = 0.0
    dot_damage: float = 0.0
    dot_duration: float = 0.0
    spell_travel_time: float = 0.0
    minimum_range: float = 0.0  # Mortar/X-Bow can't hit point-blank
    death_damage: float = 0.0  # explosion on death (Golem line, etc.)
    death_damage_radius: float = 0.0

    @property
    def attack_interval(self) -> float:
        return self.hit_speed


CARD_DEFS: dict[CardType, CardDef] = {
    CardType.KNIGHT: CardDef(
        card_type=CardType.KNIGHT,
        kind=EntityKind.TROOP,
        cost=3,
        hp=1766.0,
        dps=168.3,
        damage_per_hit=202.0,
        hit_speed=1.2,
        load_time=0.7,
        speed=2.0,
        attack_range=1.2,
        sight_range=5.5,
        target_mode=TargetMode.GROUND,
        has_evolution=True,
        has_hero=True,
        mass=6,),
    CardType.ARCHERS: CardDef(
        card_type=CardType.ARCHERS,
        kind=EntityKind.TROOP,
        cost=3,
        hp=304.0,
        dps=124.4,
        damage_per_hit=112.0,
        hit_speed=0.9,
        load_time=0.7,
        speed=2.0,
        attack_range=5.0,
        sight_range=5.5,
        target_mode=TargetMode.AIR_GROUND,
        spawn_count=2,
        has_projectile=True,
        projectile_speed=10.0,
        has_evolution=True,
        spawn_hp=304.0,
        spawn_dps=124.4,
        mass=3,),
    CardType.GOBLINS: CardDef(
        card_type=CardType.GOBLINS,
        kind=EntityKind.TROOP,
        cost=2,
        hp=202.0,
        dps=109.1,
        damage_per_hit=120.0,
        hit_speed=1.1,
        load_time=0.5,
        speed=4.0,
        attack_range=0.5,
        sight_range=5.5,
        target_mode=TargetMode.GROUND,
        spawn_count=4,
        has_hero=True,
        spawn_hp=202.0,
        spawn_dps=109.1,
        mass=2,),
    CardType.GIANT: CardDef(
        card_type=CardType.GIANT,
        kind=EntityKind.TROOP,
        cost=5,
        hp=4090.0,
        dps=168.7,
        damage_per_hit=253.0,
        hit_speed=1.5,
        load_time=1.0,
        speed=1.5,
        attack_range=1.2,
        sight_range=7.5,
        target_mode=TargetMode.BUILDINGS,
        collision_radius=0.75,
        has_hero=True,
        mass=18,),
    CardType.PEKKA: CardDef(
        card_type=CardType.PEKKA,
        kind=EntityKind.TROOP,
        cost=7,
        hp=3760.0,
        dps=453.3,
        damage_per_hit=816.0,
        hit_speed=1.7,
        load_time=1.3,
        speed=1.5,
        attack_range=1.2,
        sight_range=5.0,
        target_mode=TargetMode.GROUND,
        collision_radius=0.75,
        has_evolution=True,
        mass=18,),
    CardType.MINIONS: CardDef(
        card_type=CardType.MINIONS,
        kind=EntityKind.TROOP,
        cost=3,
        hp=252.0,
        dps=111.0,
        damage_per_hit=111.0,
        hit_speed=0.7,
        load_time=0.7,
        speed=3.0,
        attack_range=2.5,
        sight_range=5.5,
        target_mode=TargetMode.AIR_GROUND,
        is_flying=True,
        spawn_count=3,
        has_projectile=True,
        spawn_hp=230.0,
        spawn_dps=89.2,
        mass=2,),
    CardType.BALLOON: CardDef(
        card_type=CardType.BALLOON,
        kind=EntityKind.TROOP,
        cost=5,
        hp=2050.0,
        dps=320.0,
        damage_per_hit=798.0,
        hit_speed=3.0,
        load_time=2.8,
        speed=2.0,
        attack_range=0.1,
        sight_range=7.7,
        target_mode=TargetMode.BUILDINGS,
        is_flying=True,
        has_hero=True,
        mass=6,
        death_damage=195.0,
        death_damage_radius=2.0,),
    CardType.WITCH: CardDef(
        card_type=CardType.WITCH,
        kind=EntityKind.TROOP,
        cost=5,
        hp=720.0,
        dps=181.0,
        damage_per_hit=127.0,
        hit_speed=0.7,
        load_time=0.2,
        speed=2.0,
        attack_range=5.5,
        sight_range=5.5,
        target_mode=TargetMode.AIR_GROUND,
        is_splash=True,
        splash_radius=1.5,
        has_projectile=True,
        has_evolution=True,
        mass=4,),
    CardType.BARBARIANS: CardDef(
        card_type=CardType.BARBARIANS,
        kind=EntityKind.TROOP,
        cost=5,
        hp=691.0,
        dps=137.1,
        damage_per_hit=192.0,
        hit_speed=1.4,
        load_time=1.0,
        speed=2.0,
        attack_range=0.7,
        sight_range=5.5,
        target_mode=TargetMode.GROUND,
        spawn_count=5,
        has_evolution=True,
        mass=4,),
    CardType.GOLEM: CardDef(
        card_type=CardType.GOLEM,
        kind=EntityKind.TROOP,
        cost=8,
        hp=5120.0,
        dps=124.8,
        damage_per_hit=312.0,
        hit_speed=2.5,
        load_time=1.5,
        speed=1.5,
        attack_range=0.75,
        sight_range=7.0,
        target_mode=TargetMode.BUILDINGS,
        deploy_time=3.0,
        collision_radius=0.75,
        death_spawn_card=CardType.GOLEM,
        death_spawn_count=2,
        death_spawn_hp=1049.0,
        death_spawn_dps=46.0,
        mass=20,
        tower_damage=388.0,),
    CardType.SKELETONS: CardDef(
        card_type=CardType.SKELETONS,
        kind=EntityKind.TROOP,
        cost=1,
        hp=81.0,
        dps=73.6,
        damage_per_hit=81.0,
        hit_speed=1.1,
        load_time=0.6,
        speed=3.0,
        attack_range=0.5,
        sight_range=5.5,
        target_mode=TargetMode.GROUND,
        spawn_count=3,
        has_evolution=True,
        mass=1,),
    CardType.VALKYRIE: CardDef(
        card_type=CardType.VALKYRIE,
        kind=EntityKind.TROOP,
        cost=4,
        hp=1908.0,
        dps=150.0,
        damage_per_hit=226.0,
        hit_speed=1.5,
        load_time=1.4,
        speed=2.0,
        attack_range=1.2,
        sight_range=5.5,
        target_mode=TargetMode.GROUND,
        is_splash=True,
        splash_radius=2.0,
        has_evolution=True,
        mass=5,),
    CardType.SKELETON_ARMY: CardDef(
        card_type=CardType.SKELETON_ARMY,
        kind=EntityKind.TROOP,
        cost=3,
        hp=81.0,
        dps=73.6,
        damage_per_hit=81.0,
        hit_speed=1.1,
        load_time=0.6,
        speed=3.0,
        attack_range=0.5,
        sight_range=5.5,
        target_mode=TargetMode.GROUND,
        spawn_count=15,
                spawn_hp=81.0,
        spawn_dps=73.6,
    ),
    CardType.BOMBER: CardDef(
        card_type=CardType.BOMBER,
        kind=EntityKind.TROOP,
        cost=2,
        hp=304.0,
        dps=125.0,
        damage_per_hit=225.0,
        hit_speed=1.8,
        load_time=1.6,
        speed=2.0,
        attack_range=4.5,
        sight_range=5.5,
        target_mode=TargetMode.GROUND,
        is_splash=True,
        splash_radius=1.5,
        has_projectile=True,
        has_evolution=True,
        mass=4,),
    CardType.MUSKETEER: CardDef(
        card_type=CardType.MUSKETEER,
        kind=EntityKind.TROOP,
        cost=4,
        hp=721.0,
        dps=197.0,
        damage_per_hit=217.0,
        hit_speed=1.1,
        load_time=0.6,
        speed=2.0,
        attack_range=6.0,
        sight_range=6.0,
        target_mode=TargetMode.AIR_GROUND,
        has_projectile=True,
        projectile_speed=13.3,
        has_evolution=True,
        has_hero=True,
        mass=5,),
    CardType.BABY_DRAGON: CardDef(
        card_type=CardType.BABY_DRAGON,
        kind=EntityKind.TROOP,
        cost=4,
        hp=1152.0,
        dps=107.3,
        damage_per_hit=161.0,
        hit_speed=1.5,
        load_time=1.2,
        speed=3.0,
        attack_range=3.5,
        sight_range=5.5,
        target_mode=TargetMode.AIR_GROUND,
        is_flying=True,
        is_splash=True,
        splash_radius=1.5,
        has_projectile=True,
        projectile_speed=10.0,
        mass=5,),
    CardType.PRINCE: CardDef(
        card_type=CardType.PRINCE,
        kind=EntityKind.TROOP,
        cost=5,
        hp=1920.0,
        dps=232.0,
        damage_per_hit=365.0,
        hit_speed=1.4,
        load_time=1.0,
        speed=2.0,
        attack_range=1.6,
        sight_range=5.5,
        target_mode=TargetMode.GROUND,
        collision_radius=0.65,
        has_charge=True,
        charge_speed=6.0,
        charge_damage_mult=2.0,
        mass=6,),
    CardType.WIZARD: CardDef(
        card_type=CardType.WIZARD,
        kind=EntityKind.TROOP,
        cost=5,
        hp=755.0,
        dps=200.7,
        damage_per_hit=281.0,
        hit_speed=1.4,
        load_time=1.0,
        speed=2.0,
        attack_range=5.5,
        sight_range=5.5,
        target_mode=TargetMode.AIR_GROUND,
        is_splash=True,
        splash_radius=1.5,
        has_projectile=True,
        projectile_speed=10.0,
        has_evolution=True,
        has_hero=True,
        mass=5,),
    CardType.MINI_PEKKA: CardDef(
        card_type=CardType.MINI_PEKKA,
        kind=EntityKind.TROOP,
        cost=4,
        hp=1216.0,
        dps=376.0,
        damage_per_hit=640.0,
        hit_speed=1.7,
        load_time=1.3,
        speed=3.0,
        attack_range=0.8,
        sight_range=5.5,
        target_mode=TargetMode.GROUND,
        collision_radius=0.45,
        mass=4,),
    CardType.SPEAR_GOBLINS: CardDef(
        card_type=CardType.SPEAR_GOBLINS,
        kind=EntityKind.TROOP,
        cost=2,
        hp=133.0,
        dps=47.6,
        damage_per_hit=81.0,
        hit_speed=1.7,
        load_time=1.2,
        speed=4.0,
        attack_range=5.0,
        sight_range=5.5,
        target_mode=TargetMode.AIR_GROUND,
        spawn_count=3,
        has_projectile=True,
        projectile_speed=8.3,
        spawn_hp=133.0,
        spawn_dps=47.6,
        mass=1,),
    CardType.GIANT_SKELETON: CardDef(
        card_type=CardType.GIANT_SKELETON,
        kind=EntityKind.TROOP,
        cost=6,
        hp=3617.0,
        dps=212.3,
        damage_per_hit=276.0,
        hit_speed=1.3,
        load_time=1.0,
        speed=2.0,
        attack_range=0.8,
        sight_range=5.0,
        target_mode=TargetMode.GROUND,
        collision_radius=1.0,
        mass=15,
        death_damage=535.0,
        death_damage_radius=2.0,),
    CardType.HOG_RIDER: CardDef(
        card_type=CardType.HOG_RIDER,
        kind=EntityKind.TROOP,
        cost=4,
        hp=1697.0,
        dps=198.1,
        damage_per_hit=317.0,
        hit_speed=1.6,
        load_time=1.0,
        speed=4.0,
        attack_range=0.8,
        sight_range=9.5,
        target_mode=TargetMode.BUILDINGS,
        collision_radius=0.6,
        mass=4,),
    CardType.MINION_HORDE: CardDef(
        card_type=CardType.MINION_HORDE,
        kind=EntityKind.TROOP,
        cost=5,
        hp=252.0,
        dps=111.0,
        damage_per_hit=111.0,
        hit_speed=1.0,
        load_time=0.7,
        speed=3.0,
        attack_range=2.5,
        sight_range=5.5,
        target_mode=TargetMode.AIR_GROUND,
        is_flying=True,
        spawn_count=6,
        has_projectile=True,

    ),
    CardType.ICE_WIZARD: CardDef(
        card_type=CardType.ICE_WIZARD,
        kind=EntityKind.TROOP,
        cost=3,
        hp=689.0,
        dps=52.9,
        damage_per_hit=90.0,
        hit_speed=1.7,
        load_time=0.0,
        speed=2.0,
        attack_range=5.5,
        sight_range=5.5,
        target_mode=TargetMode.AIR_GROUND,
        is_splash=True,
        splash_radius=3.0,
        has_projectile=True,
        projectile_speed=10.0,
        mass=5,),
    CardType.ROYAL_GIANT: CardDef(
        card_type=CardType.ROYAL_GIANT,
        kind=EntityKind.TROOP,
        cost=6,
        hp=3068.0,
        dps=131.0,
        damage_per_hit=224.0,
        hit_speed=1.7,
        load_time=0.9,
        speed=1.5,
        attack_range=5.0,
        sight_range=7.5,
        target_mode=TargetMode.BUILDINGS,
        collision_radius=0.75,
        has_projectile=True,
        projectile_speed=10.0,
        has_evolution=True,
        mass=18,),
    CardType.GUARDS: CardDef(
        card_type=CardType.GUARDS,
        kind=EntityKind.TROOP,
        cost=3,
        hp=337.0,
        dps=117.0,
        damage_per_hit=117.0,
        hit_speed=1.0,
        load_time=0.5,
        speed=3.0,
        attack_range=1.6,
        sight_range=5.5,
        target_mode=TargetMode.GROUND,
        spawn_count=3,
        spawn_hp=81.0,
        spawn_dps=117.0,
        has_shield=True,
        shield_hp=244.0,
        mass=1,),
    CardType.PRINCESS: CardDef(
        card_type=CardType.PRINCESS,
        kind=EntityKind.TROOP,
        cost=3,
        hp=261.0,
        dps=56.0,
        damage_per_hit=168.0,
        hit_speed=3.0,
        load_time=2.7,
        speed=2.0,
        attack_range=9.0,
        sight_range=9.5,
        target_mode=TargetMode.AIR_GROUND,
        is_splash=True,
        splash_radius=2.5,
        deploy_time=1.2,
        has_projectile=True,
        projectile_speed=6.7,
        mass=3,),
    CardType.DARK_PRINCE: CardDef(
        card_type=CardType.DARK_PRINCE,
        kind=EntityKind.TROOP,
        cost=4,
        hp=1440.0,
        dps=204.0,
        damage_per_hit=266.0,
        hit_speed=1.3,
        load_time=1.0,
        speed=2.0,
        attack_range=1.2,
        sight_range=5.5,
        target_mode=TargetMode.GROUND,
        is_splash=True,
        splash_radius=1.1,
        collision_radius=0.6,
        has_hero=True,
        has_charge=True,
        charge_speed=6.0,
        charge_damage_mult=2.0,
        has_shield=True,
        shield_hp=244.0,
        mass=6,),
    CardType.THREE_MUSKETEERS: CardDef(
        card_type=CardType.THREE_MUSKETEERS,
        kind=EntityKind.TROOP,
        cost=9,
        hp=722.0,
        dps=218.0,
        damage_per_hit=218.0,
        hit_speed=1.0,
        load_time=0.0,
        speed=2.0,
        attack_range=6.0,
        sight_range=5.5,
        target_mode=TargetMode.AIR_GROUND,
        spawn_count=3,
        has_projectile=True,
        projectile_speed=13.3,
    ),
    CardType.LAVA_HOUND: CardDef(
        card_type=CardType.LAVA_HOUND,
        kind=EntityKind.TROOP,
        cost=7,
        hp=3581.0,
        dps=40.8,
        damage_per_hit=53.0,
        hit_speed=1.3,
        load_time=0.3,
        speed=1.5,
        attack_range=3.5,
        sight_range=5.5,
        target_mode=TargetMode.BUILDINGS,
        is_flying=True,
        collision_radius=0.75,
        has_projectile=True,
        death_spawn_card=CardType.LAVA_HOUND,
        death_spawn_count=6,
        death_spawn_hp=216.0,
        death_spawn_dps=54.0,
        mass=5,),
    CardType.ICE_SPIRIT: CardDef(
        card_type=CardType.ICE_SPIRIT,
        kind=EntityKind.TROOP,
        cost=1,
        hp=230.0,
        dps=366.7,
        damage_per_hit=110.0,
        hit_speed=0.3,
        load_time=0.1,
        speed=4.0,
        attack_range=2.5,
        sight_range=5.5,
        target_mode=TargetMode.AIR_GROUND,
        is_splash=True,
        splash_radius=1.5,
        collision_radius=0.4,
        has_projectile=True,
        has_evolution=True,
        stuns=True,
        stun_duration=1.5,
        mass=1,),
    CardType.FIRE_SPIRIT: CardDef(
        card_type=CardType.FIRE_SPIRIT,
        kind=EntityKind.TROOP,
        cost=1,
        hp=230.0,
        dps=690.0,
        damage_per_hit=207.0,
        hit_speed=0.3,
        load_time=0.1,
        speed=4.0,
        attack_range=2.5,
        sight_range=5.5,
        target_mode=TargetMode.AIR_GROUND,
        is_splash=True,
        splash_radius=2.3,
        collision_radius=0.4,
        has_projectile=True,
        mass=1,),
    CardType.MINER: CardDef(
        card_type=CardType.MINER,
        kind=EntityKind.TROOP,
        cost=3,
        hp=1231.0,
        dps=146.0,
        damage_per_hit=181.0,
        hit_speed=1.2,
        load_time=0.8,
        speed=3.0,
        attack_range=1.2,
        sight_range=5.5,
        target_mode=TargetMode.GROUND,
        mass=6,),
    CardType.SPARKY: CardDef(
        card_type=CardType.SPARKY,
        kind=EntityKind.TROOP,
        cost=6,
        hp=1600.0,
        dps=357.0,
        damage_per_hit=1430.0,
        hit_speed=5.0,
        load_time=4.5,
        speed=1.5,
        attack_range=5.0,
        sight_range=5.0,
        target_mode=TargetMode.GROUND,
        is_splash=True,
        splash_radius=1.8,
        collision_radius=1.0,
        has_projectile=True,
        projectile_speed=6.0,
        stuns=True,
        stun_duration=0.5,
        mass=18,),
    CardType.BOWLER: CardDef(
        card_type=CardType.BOWLER,
        kind=EntityKind.TROOP,
        cost=5,
        hp=2520.0,
        dps=115.6,
        damage_per_hit=289.0,
        hit_speed=2.5,
        load_time=2.0,
        speed=1.5,
        attack_range=4.0,
        sight_range=5.5,
        target_mode=TargetMode.GROUND,
        is_splash=True,
        splash_radius=1.8,
        collision_radius=0.75,
        has_projectile=True,
        projectile_speed=5.0,
        has_hero=True,
        mass=18,),
    CardType.LUMBERJACK: CardDef(
        card_type=CardType.LUMBERJACK,
        kind=EntityKind.TROOP,
        cost=4,
        hp=1282.0,
        dps=320.0,
        damage_per_hit=256.0,
        hit_speed=0.8,
        load_time=0.7,
        speed=4.0,
        attack_range=0.7,
        sight_range=5.5,
        target_mode=TargetMode.GROUND,
        has_evolution=True,
        mass=4,),
    CardType.BATTLE_RAM: CardDef(
        card_type=CardType.BATTLE_RAM,
        kind=EntityKind.TROOP,
        cost=4,
        hp=967.0,
        dps=0.0,
        damage_per_hit=286.0,
        hit_speed=1.4,
        load_time=1.0,
        speed=2.0,
        attack_range=0.7,
        sight_range=5.5,
        target_mode=TargetMode.BUILDINGS,
        has_evolution=True,
    ),
    CardType.INFERNO_DRAGON: CardDef(
        card_type=CardType.INFERNO_DRAGON,
        kind=EntityKind.TROOP,
        cost=4,
        hp=1295.0,
        dps=87.5,
        damage_per_hit=35.0,
        hit_speed=0.4,
        load_time=1.2,
        speed=2.0,
        attack_range=3.5,
        sight_range=5.5,
        target_mode=TargetMode.AIR_GROUND,
        is_flying=True,
        has_evolution=True,
        mass=4,),
    CardType.ICE_GOLEM: CardDef(
        card_type=CardType.ICE_GOLEM,
        kind=EntityKind.TROOP,
        cost=2,
        hp=1315.0,
        dps=33.6,
        damage_per_hit=84.0,
        hit_speed=2.5,
        load_time=1.5,
        speed=1.5,
        attack_range=0.75,
        sight_range=7.0,
        target_mode=TargetMode.BUILDINGS,
        collision_radius=0.7,
        has_hero=True,
        mass=8,
        tower_damage=113.0,),
    CardType.MEGA_MINION: CardDef(
        card_type=CardType.MEGA_MINION,
        kind=EntityKind.TROOP,
        cost=3,
        hp=837.0,
        dps=208.0,
        damage_per_hit=312.0,
        hit_speed=1.5,
        load_time=1.1,
        speed=2.0,
        attack_range=1.6,
        sight_range=5.5,
        target_mode=TargetMode.AIR_GROUND,
        is_flying=True,
        collision_radius=0.6,
        has_projectile=True,
        projectile_speed=16.7,
        has_hero=True,
        mass=5,),
    CardType.DART_GOBLIN: CardDef(
        card_type=CardType.DART_GOBLIN,
        kind=EntityKind.TROOP,
        cost=3,
        hp=261.0,
        dps=188.8,
        damage_per_hit=151.0,
        hit_speed=0.8,
        load_time=0.45,
        speed=4.0,
        attack_range=6.5,
        sight_range=7.0,
        target_mode=TargetMode.AIR_GROUND,
        has_projectile=True,
        projectile_speed=13.3,
        has_evolution=True,
        mass=2,),
    CardType.GOBLIN_GANG: CardDef(
        card_type=CardType.GOBLIN_GANG,
        kind=EntityKind.TROOP,
        cost=3,
        hp=202.0,
        dps=109.1,
        damage_per_hit=120.0,
        hit_speed=1.1,
        load_time=0.5,
        speed=4.0,
        attack_range=0.5,
        sight_range=5.5,
        target_mode=TargetMode.AIR_GROUND,
        spawn_count=6,
        has_projectile=True,
    ),
    CardType.ELECTRO_WIZARD: CardDef(
        card_type=CardType.ELECTRO_WIZARD,
        kind=EntityKind.TROOP,
        cost=4,
        hp=723.0,
        dps=65.6,
        damage_per_hit=119.0,
        hit_speed=1.8,
        load_time=0.0,
        speed=3.0,
        attack_range=5.0,
        sight_range=5.5,
        target_mode=TargetMode.AIR_GROUND,
        is_splash=True,
        splash_radius=3.0,
        stuns=True,
        stun_duration=0.5,
        resets_inferno=True,
        mass=4,
        has_projectile=True,
        projectile_speed=13.3,),
    CardType.ELITE_BARBARIANS: CardDef(
        card_type=CardType.ELITE_BARBARIANS,
        kind=EntityKind.TROOP,
        cost=6,
        hp=1341.0,
        dps=274.3,
        damage_per_hit=384.0,
        hit_speed=1.4,
        load_time=0.9,
        speed=3.0,
        attack_range=1.2,
        sight_range=6.0,
        target_mode=TargetMode.GROUND,
        spawn_count=2,
    ),
    CardType.HUNTER: CardDef(
        card_type=CardType.HUNTER,
        kind=EntityKind.TROOP,
        cost=4,
        hp=885.0,
        dps=38.2,
        damage_per_hit=84.0,
        hit_speed=2.2,
        load_time=1.5,
        speed=2.0,
        attack_range=4.0,
        sight_range=5.5,
        target_mode=TargetMode.AIR_GROUND,
        is_splash=True,
        splash_radius=0.1,
        collision_radius=0.6,
        has_projectile=True,
        projectile_speed=9.2,
        has_evolution=True,
        mass=5,),
    CardType.EXECUTIONER: CardDef(
        card_type=CardType.EXECUTIONER,
        kind=EntityKind.TROOP,
        cost=5,
        hp=1280.0,
        dps=74.6,
        damage_per_hit=168.0,
        hit_speed=2.4,
        load_time=0.4,
        speed=2.0,
        attack_range=4.5,
        sight_range=5.5,
        target_mode=TargetMode.AIR_GROUND,
        is_splash=True,
        splash_radius=1.0,
        collision_radius=0.6,
        has_projectile=True,
        projectile_speed=6.7,
        has_evolution=True,
        mass=5,),
    CardType.BANDIT: CardDef(
        card_type=CardType.BANDIT,
        kind=EntityKind.TROOP,
        cost=3,
        hp=980.0,
        dps=194.0,
        damage_per_hit=216.0,
        hit_speed=1.0,
        load_time=0.6,
        speed=3.0,
        attack_range=0.75,
        sight_range=6.0,
        target_mode=TargetMode.GROUND,
        collision_radius=0.6,
        has_charge=True,
        charge_speed=7.5,
        charge_damage_mult=1.5,
    ),
    CardType.ROYAL_RECRUITS: CardDef(
        card_type=CardType.ROYAL_RECRUITS,
        kind=EntityKind.TROOP,
        cost=7,
        hp=547.0,
        dps=102.3,
        damage_per_hit=133.0,
        hit_speed=1.3,
        load_time=0.8,
        speed=2.0,
        attack_range=1.6,
        sight_range=5.5,
        target_mode=TargetMode.GROUND,
        spawn_count=6,
        has_evolution=True,
    ),
    CardType.NIGHT_WITCH: CardDef(
        card_type=CardType.NIGHT_WITCH,
        kind=EntityKind.TROOP,
        cost=4,
        hp=870.0,
        dps=173.0,
        damage_per_hit=260.0,
        hit_speed=1.5,
        load_time=0.55,
        speed=2.0,
        attack_range=1.6,
        sight_range=5.5,
        target_mode=TargetMode.AIR_GROUND,
    ),
    CardType.BATS: CardDef(
        card_type=CardType.BATS,
        kind=EntityKind.TROOP,
        cost=2,
        hp=81.0,
        dps=67.5,
        damage_per_hit=81.0,
        hit_speed=1.2,
        load_time=0.6,
        speed=4.0,
        attack_range=1.2,
        sight_range=5.5,
        target_mode=TargetMode.AIR_GROUND,
        is_flying=True,
        spawn_count=5,
        has_evolution=True,
    ),
    CardType.ROYAL_GHOST: CardDef(
        card_type=CardType.ROYAL_GHOST,
        kind=EntityKind.TROOP,
        cost=3,
        hp=1012.0,
        dps=145.0,
        damage_per_hit=242.0,
        hit_speed=1.8,
        load_time=1.2,
        speed=3.0,
        attack_range=1.2,
        sight_range=5.5,
        target_mode=TargetMode.GROUND,
        is_splash=True,
        splash_radius=1.0,
        collision_radius=0.6,

    ),
    CardType.RAM_RIDER: CardDef(
        card_type=CardType.RAM_RIDER,
        kind=EntityKind.TROOP,
        cost=5,
        hp=1651.0,
        dps=131.0,
        damage_per_hit=210.0,
        hit_speed=1.6,
        load_time=1.1,
        speed=2.0,
        attack_range=0.8,
        sight_range=7.5,
        target_mode=TargetMode.AIR_GROUND,
        collision_radius=0.6,
    ),
    CardType.ZAPPIES: CardDef(
        card_type=CardType.ZAPPIES,
        kind=EntityKind.TROOP,
        cost=4,
        hp=529.0,
        dps=55.7,
        damage_per_hit=117.0,
        hit_speed=2.1,
        load_time=1.3,
        speed=2.0,
        attack_range=4.5,
        sight_range=5.0,
        target_mode=TargetMode.AIR_GROUND,
        spawn_count=3,
        collision_radius=0.6,
    ),
    CardType.RASCALS: CardDef(
        card_type=CardType.RASCALS,
        kind=EntityKind.TROOP,
        cost=5,
        hp=1098.0,
        dps=111.0,
        damage_per_hit=145.0,
        hit_speed=1.3,
        load_time=1.1,
        speed=2.0,
        attack_range=0.8,
        sight_range=5.5,
        target_mode=TargetMode.AIR_GROUND,
        spawn_count=3,
        collision_radius=0.75,
        has_projectile=True,
    ),
    CardType.CANNON_CART: CardDef(
        card_type=CardType.CANNON_CART,
        kind=EntityKind.TROOP,
        cost=5,
        hp=1809.0,
        dps=235.6,
        damage_per_hit=212.0,
        hit_speed=0.9,
        load_time=0.4,
        speed=2.0,
        attack_range=5.5,
        sight_range=6.0,
        target_mode=TargetMode.GROUND,
        collision_radius=0.6,
        has_projectile=True,
    ),
    CardType.MEGA_KNIGHT: CardDef(
        card_type=CardType.MEGA_KNIGHT,
        kind=EntityKind.TROOP,
        cost=7,
        hp=3993.0,
        dps=157.6,
        damage_per_hit=268.0,
        hit_speed=1.7,
        load_time=1.2,
        speed=2.0,
        attack_range=1.2,
        sight_range=5.5,
        target_mode=TargetMode.GROUND,
        is_splash=True,
        splash_radius=1.3,
        collision_radius=0.75,
        has_projectile=True,
        has_evolution=True,
        mass=15,),
    CardType.SKELETON_BARREL: CardDef(
        card_type=CardType.SKELETON_BARREL,
        kind=EntityKind.TROOP,
        cost=3,
        hp=532.0,
        dps=73.6,
        damage_per_hit=81.0,
        hit_speed=1.1,
        load_time=0.2,
        speed=3.0,
        attack_range=0.0,
        sight_range=7.7,
        target_mode=TargetMode.BUILDINGS,
        is_flying=True,

    ),
    CardType.FLYING_MACHINE: CardDef(
        card_type=CardType.FLYING_MACHINE,
        kind=EntityKind.TROOP,
        cost=4,
        hp=614.0,
        dps=155.5,
        damage_per_hit=171.0,
        hit_speed=1.1,
        load_time=0.6,
        speed=3.0,
        attack_range=6.0,
        sight_range=6.0,
        target_mode=TargetMode.AIR_GROUND,
        is_flying=True,
        has_projectile=True,
        projectile_speed=13.3,
        mass=3,),
    CardType.WALL_BREAKERS: CardDef(
        card_type=CardType.WALL_BREAKERS,
        kind=EntityKind.TROOP,
        cost=2,
        hp=330.0,
        dps=291.7,
        damage_per_hit=350.0,
        hit_speed=1.2,
        load_time=1.0,
        speed=4.0,
        attack_range=0.5,
        sight_range=7.0,
        target_mode=TargetMode.BUILDINGS,
        is_splash=True,
        splash_radius=1.5,
        spawn_count=2,
        collision_radius=0.4,
        has_projectile=True,
        has_evolution=True,
    ),
    CardType.ROYAL_HOGS: CardDef(
        card_type=CardType.ROYAL_HOGS,
        kind=EntityKind.TROOP,
        cost=5,
        hp=837.0,
        dps=61.7,
        damage_per_hit=74.0,
        hit_speed=1.2,
        load_time=0.8,
        speed=4.0,
        attack_range=0.75,
        sight_range=9.5,
        target_mode=TargetMode.BUILDINGS,
        spawn_count=4,
        collision_radius=0.6,
        has_evolution=True,
    ),
    CardType.GOBLIN_GIANT: CardDef(
        card_type=CardType.GOBLIN_GIANT,
        kind=EntityKind.TROOP,
        cost=6,
        hp=3110.0,
        dps=117.3,
        damage_per_hit=176.0,
        hit_speed=1.5,
        load_time=0.7,
        speed=2.0,
        attack_range=1.2,
        sight_range=7.5,
        target_mode=TargetMode.AIR_GROUND,
        collision_radius=0.75,
        has_evolution=True,
        mass=18,),
    CardType.FISHERMAN: CardDef(
        card_type=CardType.FISHERMAN,
        kind=EntityKind.TROOP,
        cost=3,
        hp=870.0,
        dps=149.2,
        damage_per_hit=194.0,
        hit_speed=1.3,
        load_time=1.2,
        speed=2.0,
        attack_range=1.2,
        sight_range=7.5,
        target_mode=TargetMode.GROUND,
    ),
    CardType.MAGIC_ARCHER: CardDef(
        card_type=CardType.MAGIC_ARCHER,
        kind=EntityKind.TROOP,
        cost=4,
        hp=529.0,
        dps=130.0,
        damage_per_hit=143.0,
        hit_speed=1.1,
        load_time=0.4,
        speed=2.0,
        attack_range=7.0,
        sight_range=7.5,
        target_mode=TargetMode.AIR_GROUND,
        is_splash=True,
        splash_radius=0.3,
        collision_radius=0.6,
        has_projectile=True,
        projectile_speed=16.7,
        has_hero=True,
        mass=3,),
    CardType.ELECTRO_DRAGON: CardDef(
        card_type=CardType.ELECTRO_DRAGON,
        kind=EntityKind.TROOP,
        cost=5,
        hp=949.0,
        dps=91.4,
        damage_per_hit=192.0,
        hit_speed=2.1,
        load_time=1.4,
        speed=2.0,
        attack_range=3.5,
        sight_range=5.5,
        target_mode=TargetMode.AIR_GROUND,
        is_flying=True,
        collision_radius=0.6,
        has_projectile=True,
        projectile_speed=10.0,
        has_evolution=True,
        mass=5,),
    CardType.FIRECRACKER: CardDef(
        card_type=CardType.FIRECRACKER,
        kind=EntityKind.TROOP,
        cost=3,
        hp=304.0,
        dps=21.3,
        damage_per_hit=64.0,
        hit_speed=3.0,
        load_time=2.35,
        speed=3.0,
        attack_range=6.0,
        sight_range=8.0,
        target_mode=TargetMode.AIR_GROUND,
        has_projectile=True,
        projectile_speed=10.0,
        has_evolution=True,
        mass=3,),
    CardType.MIGHTY_MINER: CardDef(
        card_type=CardType.MIGHTY_MINER,
        kind=EntityKind.TROOP,
        cost=4,
        hp=2250.0,
        dps=100.0,
        damage_per_hit=40.0,
        hit_speed=0.4,
        load_time=0.7,
        speed=2.0,
        attack_range=1.6,
        sight_range=5.5,
        target_mode=TargetMode.GROUND,
        is_champion=True,
        # "Drop Bomb": plant a delayed high-damage explosion and burrow forward.
        ability_cost=1,
        ability_cooldown=11.0,
    ),
    CardType.ELIXIR_GOLEM: CardDef(
        card_type=CardType.ELIXIR_GOLEM,
        kind=EntityKind.TROOP,
        cost=3,
        hp=1569.0,
        dps=230.0,
        damage_per_hit=253.0,
        hit_speed=1.1,
        load_time=0.3,
        speed=1.5,
        attack_range=0.8,
        sight_range=7.5,
        target_mode=TargetMode.BUILDINGS,
        collision_radius=0.6,
    ),
    CardType.BATTLE_HEALER: CardDef(
        card_type=CardType.BATTLE_HEALER,
        kind=EntityKind.TROOP,
        cost=4,
        hp=1717.0,
        dps=98.7,
        damage_per_hit=148.0,
        hit_speed=1.5,
        load_time=1.2,
        speed=2.0,
        attack_range=1.6,
        sight_range=5.5,
        target_mode=TargetMode.GROUND,
        is_splash=True,
        splash_radius=2.5,
    ),
    CardType.SKELETON_KING: CardDef(
        card_type=CardType.SKELETON_KING,
        kind=EntityKind.TROOP,
        cost=4,
        hp=2298.0,
        dps=127.5,
        damage_per_hit=204.0,
        hit_speed=1.6,
        load_time=1.3,
        speed=2.0,
        attack_range=1.2,
        sight_range=5.5,
        target_mode=TargetMode.GROUND,
        is_splash=True,
        splash_radius=1.3,
        collision_radius=1.0,
        is_champion=True,
        # "Soul Summoning": for 2 elixir the King raises a swarm of skeletons.
        ability_cost=2,
        ability_cooldown=16.0,
    ),
    CardType.ARCHER_QUEEN: CardDef(
        card_type=CardType.ARCHER_QUEEN,
        kind=EntityKind.TROOP,
        cost=5,
        hp=1000.0,
        dps=187.5,
        damage_per_hit=225.0,
        hit_speed=1.2,
        load_time=0.9,
        speed=2.0,
        attack_range=5.0,
        sight_range=5.5,
        target_mode=TargetMode.AIR_GROUND,
        has_projectile=True,
        is_champion=True,
        # "Cloaking Cape": go invisible and fire faster for 3.5s.
        ability_cost=1,
        ability_cooldown=14.0,
        ability_duration=3.5,
    ),
    CardType.GOLDEN_KNIGHT: CardDef(
        card_type=CardType.GOLDEN_KNIGHT,
        kind=EntityKind.TROOP,
        cost=4,
        hp=1799.0,
        dps=178.9,
        damage_per_hit=161.0,
        hit_speed=0.9,
        load_time=0.7,
        speed=2.0,
        attack_range=1.2,
        sight_range=5.5,
        target_mode=TargetMode.GROUND,
        collision_radius=0.8,
        is_champion=True,
        # "Dashing Dash": dash through a line of enemies dealing hit damage.
        ability_cost=1,
        ability_cooldown=12.0,
    ),
    CardType.MONK: CardDef(
        card_type=CardType.MONK,
        kind=EntityKind.TROOP,
        cost=5,
        hp=2214.0,
        dps=175.0,
        damage_per_hit=140.0,
        hit_speed=0.8,
        load_time=0.6,
        speed=2.0,
        attack_range=1.2,
        sight_range=5.5,
        target_mode=TargetMode.GROUND,
        is_champion=True,
        # "Pensive Protection": sharply reduce incoming damage for 3.5s.
        ability_cost=1,
        ability_cooldown=12.0,
        ability_duration=3.5,
    ),
    CardType.SKELETON_DRAGONS: CardDef(
        card_type=CardType.SKELETON_DRAGONS,
        kind=EntityKind.TROOP,
        cost=4,
        hp=560.0,
        dps=75.5,
        damage_per_hit=151.0,
        hit_speed=2.0,
        load_time=1.6,
        speed=3.0,
        attack_range=3.5,
        sight_range=5.5,
        target_mode=TargetMode.AIR_GROUND,
        is_flying=True,
        is_splash=True,
        splash_radius=1.5,
        spawn_count=2,
        collision_radius=0.9,
        has_projectile=True,
    ),
    CardType.MOTHER_WITCH: CardDef(
        card_type=CardType.MOTHER_WITCH,
        kind=EntityKind.TROOP,
        cost=4,
        hp=529.0,
        dps=133.0,
        damage_per_hit=133.0,
        hit_speed=1.0,
        load_time=0.7,
        speed=2.0,
        attack_range=5.5,
        sight_range=5.5,
        target_mode=TargetMode.AIR_GROUND,
        has_projectile=True,
    ),
    CardType.ELECTRO_SPIRIT: CardDef(
        card_type=CardType.ELECTRO_SPIRIT,
        kind=EntityKind.TROOP,
        cost=1,
        hp=230.0,
        dps=330.0,
        damage_per_hit=99.0,
        hit_speed=0.3,
        load_time=0.1,
        speed=4.0,
        attack_range=2.5,
        sight_range=5.5,
        target_mode=TargetMode.AIR_GROUND,
        collision_radius=0.4,
        has_projectile=True,
    ),
    CardType.ELECTRO_GIANT: CardDef(
        card_type=CardType.ELECTRO_GIANT,
        kind=EntityKind.TROOP,
        cost=7,
        hp=3855.0,
        dps=90.6,
        damage_per_hit=163.0,
        hit_speed=1.8,
        load_time=0.8,
        speed=1.5,
        attack_range=1.2,
        sight_range=7.5,
        target_mode=TargetMode.BUILDINGS,
        collision_radius=0.75,
    ),
    CardType.PHOENIX: CardDef(
        card_type=CardType.PHOENIX,
        kind=EntityKind.TROOP,
        cost=4,
        hp=1052.0,
        dps=217.0,
        damage_per_hit=217.0,
        hit_speed=1.0,
        load_time=0.4,
        speed=2.0,
        attack_range=1.6,
        sight_range=5.5,
        target_mode=TargetMode.AIR_GROUND,
        is_flying=True,
    ),
    CardType.LITTLE_PRINCE: CardDef(
        card_type=CardType.LITTLE_PRINCE,
        kind=EntityKind.TROOP,
        cost=3,
        hp=698.0,
        dps=86.7,
        damage_per_hit=104.0,
        hit_speed=1.2,
        load_time=0.8,
        speed=2.0,
        attack_range=5.5,
        sight_range=5.5,
        target_mode=TargetMode.AIR_GROUND,
        has_projectile=True,
        is_champion=True,
        # "Royal Rescue": summon his Guardienne to fight alongside him.
        ability_cost=1,
        ability_cooldown=20.0,
    ),
    CardType.GOBLIN_DEMOLISHER: CardDef(
        card_type=CardType.GOBLIN_DEMOLISHER,
        kind=EntityKind.TROOP,
        cost=4,
        hp=1300.0,
        dps=169.1,
        damage_per_hit=186.0,
        hit_speed=1.1,
        load_time=0.6,
        speed=2.0,
        attack_range=5.0,
        sight_range=5.5,
        target_mode=TargetMode.GROUND,
        is_splash=True,
        splash_radius=1.5,
        collision_radius=0.6,
        has_projectile=True,
    ),
    CardType.GOBLIN_MACHINE: CardDef(
        card_type=CardType.GOBLIN_MACHINE,
        kind=EntityKind.TROOP,
        cost=5,
        hp=2150.0,
        dps=176.7,
        damage_per_hit=212.0,
        hit_speed=1.2,
        load_time=0.7,
        speed=2.0,
        attack_range=1.2,
        sight_range=5.5,
        target_mode=TargetMode.GROUND,
        collision_radius=0.75,
    ),
    CardType.SUSPICIOUS_BUSH: CardDef(
        card_type=CardType.SUSPICIOUS_BUSH,
        kind=EntityKind.TROOP,
        cost=2,
        hp=81.0,
        dps=182.9,
        damage_per_hit=256.0,
        hit_speed=1.4,
        load_time=0.3,
        speed=2.0,
        attack_range=0.0,
        sight_range=7.5,
        target_mode=TargetMode.BUILDINGS,
    ),
    CardType.GOBLINSTEIN: CardDef(
        card_type=CardType.GOBLINSTEIN,
        kind=EntityKind.TROOP,
        cost=5,
        hp=2385.0,
        dps=85.3,
        damage_per_hit=128.0,
        hit_speed=1.5,
        load_time=0.7,
        speed=2.0,
        attack_range=1.2,
        sight_range=7.5,
        target_mode=TargetMode.AIR_GROUND,
        spawn_count=2,
        collision_radius=0.75,
        has_projectile=True,
    ),
    CardType.RUNE_GIANT: CardDef(
        card_type=CardType.RUNE_GIANT,
        kind=EntityKind.TROOP,
        cost=4,
        hp=2662.0,
        dps=102.0,
        damage_per_hit=153.0,
        hit_speed=1.5,
        load_time=1.0,
        speed=2.0,
        attack_range=1.2,
        sight_range=7.5,
        target_mode=TargetMode.BUILDINGS,
        collision_radius=0.75,
    ),
    CardType.BERSERKER: CardDef(
        card_type=CardType.BERSERKER,
        kind=EntityKind.TROOP,
        cost=2,
        hp=896.0,
        dps=170.0,
        damage_per_hit=102.0,
        hit_speed=0.6,
        load_time=0.4,
        speed=3.0,
        attack_range=0.0,
        sight_range=5.5,
        target_mode=TargetMode.GROUND,
        collision_radius=0.45,
    ),
    CardType.BOSS_BANDIT: CardDef(
        card_type=CardType.BOSS_BANDIT,
        kind=EntityKind.TROOP,
        cost=6,
        hp=2624.0,
        dps=222.7,
        damage_per_hit=245.0,
        hit_speed=1.1,
        load_time=0.7,
        speed=3.0,
        attack_range=0.8,
        sight_range=6.0,
        target_mode=TargetMode.GROUND,
        collision_radius=0.6,
    ),
    CardType.CANNON: CardDef(
        card_type=CardType.CANNON,
        kind=EntityKind.BUILDING,
        cost=3,
        hp=742.0,
        dps=265.0,
        damage_per_hit=212.0,
        hit_speed=0.8,
        load_time=0.1,
        speed=0.0,
        attack_range=5.5,
        sight_range=5.5,
        target_mode=TargetMode.GROUND,
        collision_radius=0.6,
        has_projectile=True,
        building_lifetime=30.0,
        has_evolution=True,
    ),
    CardType.GOBLIN_HUT: CardDef(
        card_type=CardType.GOBLIN_HUT,
        kind=EntityKind.BUILDING,
        cost=4,
        hp=908.0,
        dps=6.7,
        damage_per_hit=67.0,
        hit_speed=10.0,
        load_time=0.0,
        speed=4.0,
        attack_range=0.0,
        sight_range=5.5,
        target_mode=TargetMode.AIR_GROUND,
        collision_radius=1.0,
        building_lifetime=29.0,
    ),
    CardType.MORTAR: CardDef(
        card_type=CardType.MORTAR,
        kind=EntityKind.BUILDING,
        cost=4,
        hp=1369.0,
        dps=53.2,
        damage_per_hit=266.0,
        hit_speed=5.0,
        load_time=4.0,
        speed=0.0,
        attack_range=11.5,
        sight_range=11.5,
        target_mode=TargetMode.GROUND,
        is_splash=True,
        splash_radius=2.0,
        deploy_time=3.5,
        collision_radius=0.6,
        has_projectile=True,
        building_lifetime=30.0,
        has_evolution=True,
    ),
    CardType.INFERNO_TOWER: CardDef(
        card_type=CardType.INFERNO_TOWER,
        kind=EntityKind.BUILDING,
        cost=5,
        hp=1408.0,
        dps=87.0,
        damage_per_hit=35.0,
        hit_speed=0.4,
        load_time=1.2,
        speed=0.0,
        attack_range=6.0,
        sight_range=6.0,
        target_mode=TargetMode.AIR_GROUND,
        collision_radius=0.6,
        building_lifetime=30.0,
        inferno_dps_min=40.0,
        inferno_dps_max=480.0,
    ),
    CardType.BOMB_TOWER: CardDef(
        card_type=CardType.BOMB_TOWER,
        kind=EntityKind.BUILDING,
        cost=4,
        hp=1440.0,
        dps=173.0,
        damage_per_hit=277.0,
        hit_speed=1.6,
        load_time=1.3,
        speed=0.0,
        attack_range=6.0,
        sight_range=6.0,
        target_mode=TargetMode.GROUND,
        is_splash=True,
        splash_radius=1.5,
        collision_radius=0.6,
        has_projectile=True,
        building_lifetime=30.0,
    ),
    CardType.BARBARIAN_HUT: CardDef(
        card_type=CardType.BARBARIAN_HUT,
        kind=EntityKind.BUILDING,
        cost=6,
        hp=1164.0,
        dps=15.9,
        damage_per_hit=159.0,
        hit_speed=10.0,
        load_time=0.0,
        speed=0.0,
        attack_range=0.0,
        sight_range=5.5,
        target_mode=TargetMode.GROUND,
        collision_radius=1.0,
        building_lifetime=30.0,
    ),
    CardType.TESLA: CardDef(
        card_type=CardType.TESLA,
        kind=EntityKind.BUILDING,
        cost=4,
        hp=895.0,
        dps=192.0,
        damage_per_hit=212.0,
        hit_speed=1.1,
        load_time=0.7,
        speed=0.0,
        attack_range=5.5,
        sight_range=5.5,
        target_mode=TargetMode.AIR_GROUND,
        building_lifetime=25.0,
        has_evolution=True,
    ),
    CardType.ELIXIR_COLLECTOR: CardDef(
        card_type=CardType.ELIXIR_COLLECTOR,
        kind=EntityKind.BUILDING,
        cost=6,
        hp=888.0,
        dps=0.0,
        damage_per_hit=0.0,
        hit_speed=0.0,
        load_time=0.0,
        speed=0.0,
        attack_range=0.0,
        sight_range=5.5,
        target_mode=TargetMode.AIR_GROUND,
        collision_radius=1.0,
        building_lifetime=65.0,
    ),
    CardType.X_BOW: CardDef(
        card_type=CardType.X_BOW,
        kind=EntityKind.BUILDING,
        cost=6,
        hp=1292.0,
        dps=110.0,
        damage_per_hit=33.0,
        hit_speed=0.3,
        load_time=0.0,
        speed=0.0,
        attack_range=11.5,
        sight_range=11.5,
        target_mode=TargetMode.GROUND,
        deploy_time=3.5,
        collision_radius=0.6,
        has_projectile=True,
        building_lifetime=30.0,
    ),
    CardType.TOMBSTONE: CardDef(
        card_type=CardType.TOMBSTONE,
        kind=EntityKind.BUILDING,
        cost=3,
        hp=529.0,
        dps=8.1,
        damage_per_hit=81.0,
        hit_speed=10.0,
        load_time=0.0,
        speed=0.0,
        attack_range=2.0,
        sight_range=5.5,
        target_mode=TargetMode.GROUND,
        collision_radius=1.0,
        building_lifetime=30.0,
        has_hero=True,
    ),
    CardType.FURNACE: CardDef(
        card_type=CardType.FURNACE,
        kind=EntityKind.TROOP,
        cost=4,
        hp=727.0,
        dps=105.3,
        damage_per_hit=179.0,
        hit_speed=1.7,
        load_time=1.2,
        speed=2.0,
        attack_range=5.5,
        sight_range=6.0,
        target_mode=TargetMode.AIR_GROUND,
        collision_radius=0.6,
        has_projectile=True,
        has_evolution=True,
    ),
    CardType.GOBLIN_CAGE: CardDef(
        card_type=CardType.GOBLIN_CAGE,
        kind=EntityKind.BUILDING,
        cost=4,
        hp=780.0,
        dps=30.6,
        damage_per_hit=306.0,
        hit_speed=10.0,
        load_time=0.0,
        speed=0.0,
        attack_range=5.0,
        sight_range=20.0,
        target_mode=TargetMode.GROUND,
        collision_radius=1.0,
        building_lifetime=20.0,
        has_evolution=True,
    ),
    CardType.GOBLIN_DRILL: CardDef(
        card_type=CardType.GOBLIN_DRILL,
        kind=EntityKind.BUILDING,
        cost=4,
        hp=1313.0,
        dps=70.0,
        damage_per_hit=84.0,
        hit_speed=1.2,
        load_time=0.7,
        speed=2.0,
        attack_range=0.0,
        sight_range=5.5,
        target_mode=TargetMode.AIR_GROUND,
        tower_damage=26.0,
        building_lifetime=10.0,
        has_evolution=True,
    ),
    CardType.FIREBALL: CardDef(
        card_type=CardType.FIREBALL,
        kind=EntityKind.SPELL,
        cost=4,
        hp=0.0,
        dps=0.0,
        damage_per_hit=689.0,
        hit_speed=0.0,
        load_time=0.0,
        speed=2.0,
        attack_range=0.0,
        sight_range=5.5,
        target_mode=TargetMode.AIR_GROUND,
        is_splash=True,
        splash_radius=2.5,
        has_projectile=True,
        tower_damage=172.0,
        has_knockback=True,
        knockback_distance=0.5,
        spell_travel_time=1.0,
    ),
    CardType.ARROWS: CardDef(
        card_type=CardType.ARROWS,
        kind=EntityKind.SPELL,
        cost=3,
        hp=0.0,
        dps=0.0,
        damage_per_hit=322.0,
        hit_speed=0.0,
        load_time=0.0,
        speed=2.0,
        attack_range=0.0,
        sight_range=5.5,
        target_mode=TargetMode.AIR_GROUND,
        is_splash=True,
        splash_radius=3.5,
        has_projectile=True,
        tower_damage=75.0,
        spell_travel_time=3.0,
    ),
    CardType.RAGE: CardDef(
        card_type=CardType.RAGE,
        kind=EntityKind.SPELL,
        cost=2,
        hp=0.0,
        dps=0.0,
        damage_per_hit=179.0,
        hit_speed=0.0,
        load_time=0.0,
        speed=2.0,
        attack_range=0.0,
        sight_range=5.5,
        target_mode=TargetMode.AIR_GROUND,
        is_splash=True,
        splash_radius=3.0,
        tower_damage=45.0,
    ),
    CardType.ROCKET: CardDef(
        card_type=CardType.ROCKET,
        kind=EntityKind.SPELL,
        cost=6,
        hp=0.0,
        dps=0.0,
        damage_per_hit=1485.0,
        hit_speed=0.0,
        load_time=0.0,
        speed=2.0,
        attack_range=0.0,
        sight_range=5.5,
        target_mode=TargetMode.AIR_GROUND,
        is_splash=True,
        splash_radius=2.0,
        has_projectile=True,
        tower_damage=343.0,
    ),
    CardType.GOBLIN_BARREL: CardDef(
        card_type=CardType.GOBLIN_BARREL,
        kind=EntityKind.SPELL,
        cost=3,
        hp=202.0,
        dps=109.1,
        damage_per_hit=120.0,
        hit_speed=1.1,
        load_time=0.0,
        speed=2.0,
        attack_range=0.0,
        sight_range=5.5,
        target_mode=TargetMode.AIR_GROUND,
        is_splash=True,
        splash_radius=1.5,
        spawn_count=3,
        has_projectile=True,
        has_evolution=True,
        spawn_hp=202.0,
        spawn_dps=109.1,
    ),
    CardType.FREEZE: CardDef(
        card_type=CardType.FREEZE,
        kind=EntityKind.SPELL,
        cost=4,
        hp=0.0,
        dps=0.0,
        damage_per_hit=148.0,
        hit_speed=0.0,
        load_time=0.0,
        speed=2.0,
        attack_range=0.0,
        sight_range=5.5,
        target_mode=TargetMode.AIR_GROUND,
        is_splash=True,
        splash_radius=3.0,
        tower_damage=37.0,
        stuns=True,
        stun_duration=4.0,
    ),
    CardType.MIRROR: CardDef(
        card_type=CardType.MIRROR,
        kind=EntityKind.SPELL,
        cost=1,
        hp=0.0,
        dps=0.0,
        damage_per_hit=0.0,
        hit_speed=0.0,
        load_time=0.0,
        speed=0.0,
        attack_range=0.0,
        sight_range=5.5,
        target_mode=TargetMode.AIR_GROUND,
    ),
    CardType.LIGHTNING: CardDef(
        card_type=CardType.LIGHTNING,
        kind=EntityKind.SPELL,
        cost=6,
        hp=0.0,
        dps=0.0,
        damage_per_hit=1057.0,
        hit_speed=0.0,
        load_time=0.0,
        speed=0.0,
        attack_range=0.0,
        sight_range=5.5,
        target_mode=TargetMode.AIR_GROUND,
        is_splash=True,
        splash_radius=3.5,
        has_projectile=True,
        tower_damage=265.0,
        stuns=True,
        stun_duration=0.5,
        resets_inferno=True,
    ),
    CardType.ZAP: CardDef(
        card_type=CardType.ZAP,
        kind=EntityKind.SPELL,
        cost=2,
        hp=0.0,
        dps=0.0,
        damage_per_hit=192.0,
        hit_speed=0.0,
        load_time=0.0,
        speed=0.0,
        attack_range=5.0,
        sight_range=5.5,
        target_mode=TargetMode.AIR_GROUND,
        is_splash=True,
        splash_radius=2.5,
        tower_damage=48.0,
        has_evolution=True,
        stuns=True,
        stun_duration=0.5,
        resets_inferno=True,
    ),
    CardType.POISON: CardDef(
        card_type=CardType.POISON,
        kind=EntityKind.SPELL,
        cost=4,
        hp=0.0,
        dps=92.0,
        damage_per_hit=92.0,
        hit_speed=1.0,
        load_time=0.0,
        speed=0.0,
        attack_range=3.5,
        sight_range=5.5,
        target_mode=TargetMode.AIR_GROUND,
        is_splash=True,
        splash_radius=3.5,
        tower_damage=21.0,
        dot_damage=92.0,
        dot_duration=8.0,
    ),
    CardType.GRAVEYARD: CardDef(
        card_type=CardType.GRAVEYARD,
        kind=EntityKind.SPELL,
        cost=5,
        hp=82.0,
        dps=82.0,
        damage_per_hit=82.0,
        hit_speed=1.0,
        load_time=0.0,
        speed=3.0,
        attack_range=0.0,
        sight_range=5.5,
        target_mode=TargetMode.AIR_GROUND,
        is_splash=True,
        splash_radius=4.0,
        spawn_count=12,
    ),
    CardType.THE_LOG: CardDef(
        card_type=CardType.THE_LOG,
        kind=EntityKind.SPELL,
        cost=2,
        hp=0.0,
        dps=0.0,
        damage_per_hit=269.0,
        hit_speed=0.0,
        load_time=0.0,
        speed=0.0,
        attack_range=10.1,
        sight_range=5.5,
        target_mode=TargetMode.GROUND,
        is_splash=True,
        splash_radius=1.95,
        has_projectile=True,
        tower_damage=35.0,
        has_knockback=True,
        knockback_distance=1.5,
        spell_travel_time=2.5,
    ),
    CardType.TORNADO: CardDef(
        card_type=CardType.TORNADO,
        kind=EntityKind.SPELL,
        cost=3,
        hp=0.0,
        dps=0.0,
        damage_per_hit=154.0,
        hit_speed=0.0,
        load_time=0.0,
        speed=0.0,
        attack_range=5.5,
        sight_range=5.5,
        target_mode=TargetMode.AIR_GROUND,
        is_splash=True,
        splash_radius=5.5,
        tower_damage=46.0,
        dot_damage=42.0,
        dot_duration=1.0,
    ),
    CardType.CLONE: CardDef(
        card_type=CardType.CLONE,
        kind=EntityKind.SPELL,
        cost=3,
        hp=0.0,
        dps=0.0,
        damage_per_hit=0.0,
        hit_speed=0.0,
        load_time=0.0,
        speed=0.0,
        attack_range=3.0,
        sight_range=5.5,
        target_mode=TargetMode.AIR_GROUND,
        is_splash=True,
        splash_radius=3.0,
    ),
    CardType.EARTHQUAKE: CardDef(
        card_type=CardType.EARTHQUAKE,
        kind=EntityKind.SPELL,
        cost=3,
        hp=0.0,
        dps=82.0,
        damage_per_hit=82.0,
        hit_speed=1.0,
        load_time=0.0,
        speed=0.0,
        attack_range=3.5,
        sight_range=5.5,
        target_mode=TargetMode.GROUND,
        is_splash=True,
        splash_radius=3.5,
        tower_damage=49.0,
    ),
    CardType.BARBARIAN_BARREL: CardDef(
        card_type=CardType.BARBARIAN_BARREL,
        kind=EntityKind.SPELL,
        cost=2,
        hp=670.0,
        dps=179.2,
        damage_per_hit=233.0,
        hit_speed=1.3,
        load_time=0.0,
        speed=2.0,
        attack_range=4.5,
        sight_range=5.5,
        target_mode=TargetMode.GROUND,
        is_splash=True,
        splash_radius=1.3,
        has_projectile=True,
        has_hero=True,
    ),
    CardType.HEAL_SPIRIT: CardDef(
        card_type=CardType.HEAL_SPIRIT,
        kind=EntityKind.TROOP,
        cost=1,
        hp=230.0,
        dps=366.7,
        damage_per_hit=110.0,
        hit_speed=0.3,
        load_time=0.1,
        speed=4.0,
        attack_range=2.5,
        sight_range=5.5,
        target_mode=TargetMode.AIR_GROUND,
        is_splash=True,
        splash_radius=1.5,
        collision_radius=0.4,
        has_projectile=True,
    ),
    CardType.GIANT_SNOWBALL: CardDef(
        card_type=CardType.GIANT_SNOWBALL,
        kind=EntityKind.SPELL,
        cost=2,
        hp=0.0,
        dps=0.0,
        damage_per_hit=179.0,
        hit_speed=0.0,
        load_time=0.0,
        speed=0.0,
        attack_range=5.0,
        sight_range=5.5,
        target_mode=TargetMode.AIR_GROUND,
        is_splash=True,
        splash_radius=2.5,
        has_projectile=True,
        tower_damage=45.0,
        has_evolution=True,
    ),
    CardType.ROYAL_DELIVERY: CardDef(
        card_type=CardType.ROYAL_DELIVERY,
        kind=EntityKind.SPELL,
        cost=3,
        hp=548.0,
        dps=0.0,
        damage_per_hit=438.0,
        hit_speed=0.0,
        load_time=0.0,
        speed=2.0,
        attack_range=0.0,
        sight_range=5.5,
        target_mode=TargetMode.AIR_GROUND,
        is_splash=True,
        splash_radius=3.0,
        has_projectile=True,
    ),
    CardType.VOID: CardDef(
        card_type=CardType.VOID,
        kind=EntityKind.SPELL,
        cost=3,
        hp=0.0,
        dps=0.0,
        damage_per_hit=256.0,
        hit_speed=0.0,
        load_time=0.0,
        speed=2.0,
        attack_range=0.0,
        sight_range=5.5,
        target_mode=TargetMode.AIR_GROUND,
        is_splash=True,
        splash_radius=2.5,
        tower_damage=144.0,
    ),
    CardType.GOBLIN_CURSE: CardDef(
        card_type=CardType.GOBLIN_CURSE,
        kind=EntityKind.SPELL,
        cost=2,
        hp=0.0,
        dps=0.0,
        damage_per_hit=256.0,
        hit_speed=0.0,
        load_time=0.0,
        speed=2.0,
        attack_range=0.0,
        sight_range=5.5,
        target_mode=TargetMode.AIR_GROUND,
        is_splash=True,
        splash_radius=3.0,
        tower_damage=42.0,
    ),
    CardType.SPIRIT_EMPRESS: CardDef(
        card_type=CardType.SPIRIT_EMPRESS,
        kind=EntityKind.TROOP,
        cost=6,
        hp=1255.0,
        dps=219.3,
        damage_per_hit=307.0,
        hit_speed=1.4,
        load_time=0.0,
        speed=2.0,
        attack_range=4.5,
        sight_range=5.5,
        target_mode=TargetMode.AIR_GROUND,
    ),
    CardType.VINES: CardDef(
        card_type=CardType.VINES,
        kind=EntityKind.SPELL,
        cost=3,
        hp=0.0,
        dps=0.0,
        damage_per_hit=405.0,
        hit_speed=0.0,
        load_time=0.0,
        speed=0.0,
        attack_range=0.0,
        sight_range=5.5,
        target_mode=TargetMode.AIR_GROUND,
        is_splash=True,
        splash_radius=2.5,
        tower_damage=70.0,
    ),
    CardType.GOBLIN_BRAWLER: CardDef(
        card_type=CardType.GOBLIN_BRAWLER,
        kind=EntityKind.TROOP,
        cost=4,
        hp=1080.0,
        dps=306.0,
        damage_per_hit=337.0,
        hit_speed=1.1,
        load_time=0.5,
        speed=3.0,
        attack_range=0.8,
        sight_range=5.5,
        target_mode=TargetMode.GROUND,
    ),
    CardType.BUSH_GOBLINS: CardDef(
        card_type=CardType.BUSH_GOBLINS,
        kind=EntityKind.TROOP,
        cost=3,
        hp=304.0,
        dps=182.0,
        damage_per_hit=256.0,
        hit_speed=1.4,
        load_time=0.5,
        speed=3.0,
        attack_range=0.8,
        sight_range=5.5,
        target_mode=TargetMode.GROUND,
        spawn_count=2,
    ),
    CardType.CURSED_HOG: CardDef(
        card_type=CardType.CURSED_HOG,
        kind=EntityKind.TROOP,
        cost=2,
        hp=629.0,
        dps=44.0,
        damage_per_hit=53.0,
        hit_speed=1.2,
        load_time=0.5,
        speed=4.0,
        attack_range=0.75,
        sight_range=5.5,
        target_mode=TargetMode.GROUND,
    ),
    CardType.GUARDIENNE: CardDef(
        card_type=CardType.GUARDIENNE,
        kind=EntityKind.TROOP,
        cost=4,
        hp=1600.0,
        dps=180.0,
        damage_per_hit=217.0,
        hit_speed=1.2,
        load_time=0.5,
        speed=2.0,
        attack_range=1.2,
        sight_range=5.5,
        target_mode=TargetMode.GROUND,
    ),
}


NUM_CARD_TYPES: int = 125


# Overlay authentic stats from the extracted Supercell game data
# (cr_engine/gamedata_v2/*.csv) so the simulator matches the real game. The
# CSVs are the single source of truth; the literals above act as the schema
# (special-mechanic flags) and as a fallback for the few cards with no CSV
# entry. See crsim/gamedata.py.
def _apply_authentic_overlay() -> None:
    global CARD_DEFS, AUTHENTIC_STAT_REPORT
    try:
        from crsim.gamedata import apply_authentic_stats

        CARD_DEFS, AUTHENTIC_STAT_REPORT = apply_authentic_stats(CARD_DEFS)
    except Exception:  # pragma: no cover - never let data issues break import
        import logging

        logging.getLogger(__name__).exception(
            "Failed to apply authentic stat overlay; using hand-coded stats."
        )
        AUTHENTIC_STAT_REPORT = {}


AUTHENTIC_STAT_REPORT: dict = {}
_apply_authentic_overlay()
