"""Imitation warm-start CLI.

Two modes, both end-to-end runnable on CPU (launch-ready for GPU):

  # Behavioral cloning from a strong reference bot (no external data needed)
  python scripts/warmstart.py bc --games 64 --epochs 10 --out checkpoints/bc.pt

  # Value warm-start from deck-matchup outcomes (Kaggle dump, etc.)
  python scripts/warmstart.py value --battles data/battles.jsonl --out checkpoints/vw.pt

The BC dataset is generated by self-play of ``MetaAgent`` on the verified Python
engine; KataCR replays drop in by converting them to the same npz schema. The
value matchup file accepts JSONL/CSV (see ``training.imitation._load_battles``).
"""

from __future__ import annotations

import argparse
import logging
import tempfile
from pathlib import Path

import torch

from model.network import CRZeroNet
from training.imitation import (
    ExpertDataset,
    ImitationConfig,
    generate_expert_dataset,
    train_behavioral_cloning,
    train_value_warmstart,
)


def _bc(args: argparse.Namespace, device: str) -> None:
    npz = args.dataset
    if npz is None:
        npz = str(Path(tempfile.mkdtemp()) / "expert.npz")
    n = generate_expert_dataset(
        npz, n_games=args.games, backend=args.backend,
        decision_interval=args.decision_interval, max_ticks=args.max_ticks, seed=args.seed,
    )
    logging.info("Generated %d expert samples -> %s", n, npz)

    dataset = ExpertDataset(npz, max_samples=args.max_samples)
    model = CRZeroNet(n_res_blocks=args.res_blocks, n_filters=args.filters)
    cfg = ImitationConfig(
        batch_size=args.batch_size, num_epochs=args.epochs, learning_rate=args.lr,
    )
    train_behavioral_cloning(model, dataset, cfg, device)
    Path(args.out).parent.mkdir(parents=True, exist_ok=True)
    torch.save(model.state_dict(), args.out)
    logging.info("Saved behavioral-cloned model -> %s", args.out)


def _value(args: argparse.Namespace, device: str) -> None:
    model = CRZeroNet(n_res_blocks=args.res_blocks, n_filters=args.filters)
    train_value_warmstart(
        battles_path=args.battles, output_path=args.out, epochs=args.epochs,
        device=device, model=model, batch_size=args.batch_size, learning_rate=args.lr,
        max_samples=args.max_samples,
    )


def main() -> None:
    parser = argparse.ArgumentParser(description="Imitation warm-start")
    parser.add_argument("--device", default="cuda" if torch.cuda.is_available() else "cpu")
    parser.add_argument("--res-blocks", type=int, default=10)
    parser.add_argument("--filters", type=int, default=128)
    parser.add_argument("--batch-size", type=int, default=128)
    parser.add_argument("--epochs", type=int, default=10)
    parser.add_argument("--lr", type=float, default=1e-3)
    parser.add_argument("--max-samples", type=int, default=None)
    parser.add_argument("--out", required=True, help="output checkpoint path")
    sub = parser.add_subparsers(dest="mode", required=True)

    bc = sub.add_parser("bc", help="behavioral cloning from a reference bot")
    bc.add_argument("--games", type=int, default=64)
    bc.add_argument("--backend", default="python")
    bc.add_argument("--decision-interval", type=int, default=8)
    bc.add_argument("--max-ticks", type=int, default=None)
    bc.add_argument("--seed", type=int, default=0)
    bc.add_argument("--dataset", default=None, help="reuse/save expert npz here")

    val = sub.add_parser("value", help="value warm-start from deck matchups")
    val.add_argument("--battles", required=True, help="JSONL/CSV of deck matchups")

    args = parser.parse_args()
    logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s %(message)s")

    if args.mode == "bc":
        _bc(args, args.device)
    else:
        _value(args, args.device)


if __name__ == "__main__":
    main()
