[package]
name = "cr_engine"
version = "0.1.0"
edition = "2021"

[lib]
name = "cr_engine_native"
crate-type = ["cdylib", "rlib"]

[dependencies]
csv = "1.3"
serde = { version = "1.0", features = ["derive"] }
pyo3 = { version = "0.22", features = ["extension-module"], optional = true }
rand = "0.8"

[[bin]]
name = "bench"
path = "bench.rs"


[features]
default = []
python = ["pyo3"]
